name: Python Package using Conda

on:
  push:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8', '3.9', '3.10']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file config/enviroment.yml --name base
    - name: Test with pytest
      run: python main.py
    - name: Create ZIP archive
      run: |
        cd output
        zip -r qrcode.zip ./*
    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        name: QrCode
        path: qrcode.zip